# Generated by Django 5.1.5 on 2025-01-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veh_name', models.CharField(choices=[('Tata', 'Tata'), ('BMW', 'BMW'), ('HERO', 'HERO'), ('AUDI', 'AUDI')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(choices=[('petrol', 'petrol'), ('cng', 'cng'), ('dsl', 'dsl'), ('ev', 'ev')], max_length=50)),
                ('v_nm', models.ManyToManyField(to='app.vehicle')),
            ],
        ),
    ]
