# Generated by Django 5.1.4 on 2025-01-21 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPage',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('adminname', models.CharField(db_index=True, help_text='Enter a unique username', max_length=30, null=True, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('bio', models.CharField(blank=True, db_index=True, help_text='Write a short bio about yourself', max_length=50, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(choices=[('CSE', 'CSE'), ('EXE', 'EXE'), ('IT', 'IT'), ('ME', 'ME'), ('MI/MI', 'MI/MI')], max_length=100, unique=True, verbose_name='name')),
                ('description', models.TextField(max_length=200, verbose_name='Desc')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('adharno', models.IntegerField(unique=True)),
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, help_text='Enter a unique username', max_length=30, null=True, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('bio', models.CharField(blank=True, db_index=True, help_text='Write a short bio about yourself', max_length=50, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('qulification', models.CharField(choices=[('b-tech', 'b-tech'), ('m,tech', 'm-tech')], db_index=True, max_length=100, null=True, verbose_name='Quali')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1', 'B.Tech'), ('2', 'B.Com'), ('3', 'M.Com'), ('4', 'BCA'), ('5', 'M.Tech')], max_length=100, verbose_name='name')),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('stu_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.departmentmodel', to_field='dep_name')),
            ],
        ),
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, help_text='Enter a unique username', max_length=30, null=True, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('bio', models.CharField(blank=True, db_index=True, help_text='Write a short bio about yourself', max_length=50, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('qulification', models.CharField(choices=[('b-tech', 'b-tech'), ('m,tech', 'm-tech')], db_index=True, max_length=100, null=True, verbose_name='Quali')),
                ('adharno', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.userprofile')),
            ],
        ),
    ]
