# Generated by Django 5.1.4 on 2025-01-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fuel',
            fields=[
                ('fuel_name', models.CharField(choices=[('petool', 'petool'), ('EV', 'EV'), ('CNG', 'CNG'), ('Dezal', 'Dezal')], max_length=100, primary_key=True, serialize=False, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Vehical',
            fields=[
                ('car_name', models.CharField(choices=[('TATA', 'TATA'), ('HONDA', 'HONDA'), ('MARUTHI', 'MARUTHI'), ('BMW', 'BMW')], max_length=100, primary_key=True, serialize=False, verbose_name='name')),
                ('price', models.IntegerField()),
                ('fuel_name', models.ManyToManyField(to='app.fuel')),
            ],
        ),
    ]
