# Generated by Django 5.1.4 on 2025-01-08 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='resume',
            field=models.FileField(max_length=50, upload_to=''),
        ),
    ]
